# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# NOTE: old go update script https://eos2git.cec.lab.emc.com/CSM/csm-pipeline/blob/master/shell-scripts/go-automation.sh

# Reusable workflow to perform go version update on Golang based projects
name: Go Version

on:
  repository_dispatch:
    types: [go-update-workflow]

jobs:
  # go version update
  go-version:
    uses: shaynafinocchiaro/test-common-github-actions/.github/workflows/go-version.yaml@main
    name: Go Version Update
